version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BeMyValentine
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
